// 자동 생성 — tools/mypaint-gen.mjs (출처: web2/brushes/brushsettings.json · libmypaint ISC)
// 손으로 고치지 않는다. 설정 65 · 입력 18 · 상태 44.
/* eslint-disable */

export interface SettingInfo { id: string; constant: boolean; min: number; def: number; max: number; name: string }
export interface InputInfo { id: string; hardMin: number | null; softMin: number; normal: number; softMax: number; hardMax: number | null }

export const SETTINGS: readonly SettingInfo[] = [
  { id: "opaque", constant: false, min: 0, def: 1, max: 2, name: "Opacity" },
  { id: "opaque_multiply", constant: false, min: 0, def: 0, max: 2, name: "Opacity multiply" },
  { id: "opaque_linearize", constant: true, min: 0, def: 0.9, max: 2, name: "Opacity linearize" },
  { id: "radius_logarithmic", constant: false, min: -2, def: 2, max: 6, name: "Radius" },
  { id: "hardness", constant: false, min: 0, def: 0.8, max: 1, name: "Hardness" },
  { id: "softness", constant: false, min: 0, def: 0, max: 1, name: "Softness" },
  { id: "anti_aliasing", constant: false, min: 0, def: 1, max: 5, name: "Pixel feather" },
  { id: "dabs_per_basic_radius", constant: false, min: 0, def: 0, max: 200, name: "Dabs per basic radius" },
  { id: "dabs_per_actual_radius", constant: false, min: 0, def: 2, max: 200, name: "Dabs per actual radius" },
  { id: "dabs_per_second", constant: false, min: 0, def: 0, max: 200, name: "Dabs per second" },
  { id: "gridmap_scale", constant: false, min: -10, def: 0, max: 10, name: "GridMap Scale" },
  { id: "gridmap_scale_x", constant: false, min: 0, def: 1, max: 10, name: "GridMap Scale X" },
  { id: "gridmap_scale_y", constant: false, min: 0, def: 1, max: 10, name: "GridMap Scale Y" },
  { id: "radius_by_random", constant: false, min: 0, def: 0, max: 1.5, name: "Radius by random" },
  { id: "speed1_slowness", constant: false, min: 0, def: 0.04, max: 0.2, name: "Fine speed filter" },
  { id: "speed2_slowness", constant: false, min: 0, def: 0.8, max: 3, name: "Gross speed filter" },
  { id: "speed1_gamma", constant: true, min: -8, def: 4, max: 8, name: "Fine speed gamma" },
  { id: "speed2_gamma", constant: true, min: -8, def: 4, max: 8, name: "Gross speed gamma" },
  { id: "offset_by_random", constant: false, min: 0, def: 0, max: 25, name: "Jitter" },
  { id: "offset_y", constant: false, min: -40, def: 0, max: 40, name: "Offset Y" },
  { id: "offset_x", constant: false, min: -40, def: 0, max: 40, name: "Offset X" },
  { id: "offset_angle", constant: false, min: -40, def: 0, max: 40, name: "Angular Offset: Direction" },
  { id: "offset_angle_asc", constant: false, min: -40, def: 0, max: 40, name: "Angular Offset: Ascension" },
  { id: "offset_angle_view", constant: false, min: -40, def: 0, max: 40, name: "Angular Offset: View" },
  { id: "offset_angle_2", constant: false, min: 0, def: 0, max: 40, name: "Angular Offset Mirrored: Direction" },
  { id: "offset_angle_2_asc", constant: false, min: 0, def: 0, max: 40, name: "Angular Offset Mirrored: Ascension" },
  { id: "offset_angle_2_view", constant: false, min: 0, def: 0, max: 40, name: "Angular Offset Mirrored: View" },
  { id: "offset_angle_adj", constant: false, min: -180, def: 0, max: 180, name: "Angular Offsets Adjustment" },
  { id: "offset_multiplier", constant: false, min: -2, def: 0, max: 3, name: "Offsets Multiplier" },
  { id: "offset_by_speed", constant: false, min: -3, def: 0, max: 3, name: "Offset by speed" },
  { id: "offset_by_speed_slowness", constant: false, min: 0, def: 1, max: 15, name: "Offset by speed filter" },
  { id: "slow_tracking", constant: true, min: 0, def: 0, max: 10, name: "Slow position tracking" },
  { id: "slow_tracking_per_dab", constant: false, min: 0, def: 0, max: 10, name: "Slow tracking per dab" },
  { id: "tracking_noise", constant: true, min: 0, def: 0, max: 12, name: "Tracking noise" },
  { id: "color_h", constant: true, min: 0, def: 0, max: 1, name: "Color hue" },
  { id: "color_s", constant: true, min: -0.5, def: 0, max: 1.5, name: "Color saturation" },
  { id: "color_v", constant: true, min: -0.5, def: 0, max: 1.5, name: "Color value" },
  { id: "restore_color", constant: true, min: 0, def: 0, max: 1, name: "Save color" },
  { id: "change_color_h", constant: false, min: -2, def: 0, max: 2, name: "Change color hue" },
  { id: "change_color_l", constant: false, min: -2, def: 0, max: 2, name: "Change color lightness (HSL)" },
  { id: "change_color_hsl_s", constant: false, min: -2, def: 0, max: 2, name: "Change color satur. (HSL)" },
  { id: "change_color_v", constant: false, min: -2, def: 0, max: 2, name: "Change color value (HSV)" },
  { id: "change_color_hsv_s", constant: false, min: -2, def: 0, max: 2, name: "Change color satur. (HSV)" },
  { id: "smudge", constant: false, min: 0, def: 0, max: 1, name: "Smudge" },
  { id: "paint_mode", constant: false, min: 0, def: 1, max: 1, name: "Pigment" },
  { id: "smudge_transparency", constant: false, min: -1, def: 0, max: 1, name: "Smudge transparency" },
  { id: "smudge_length", constant: false, min: 0, def: 0.5, max: 1, name: "Smudge length" },
  { id: "smudge_length_log", constant: false, min: 0, def: 0, max: 20, name: "Smudge length multiplier" },
  { id: "smudge_bucket", constant: false, min: 0, def: 0, max: 255, name: "Smudge bucket" },
  { id: "smudge_radius_log", constant: false, min: -1.6, def: 0, max: 1.6, name: "Smudge radius" },
  { id: "eraser", constant: false, min: 0, def: 0, max: 1, name: "Eraser" },
  { id: "stroke_threshold", constant: true, min: 0, def: 0, max: 0.5, name: "Stroke threshold" },
  { id: "stroke_duration_logarithmic", constant: false, min: -1, def: 4, max: 14, name: "Stroke duration" },
  { id: "stroke_holdtime", constant: false, min: 0, def: 0, max: 10, name: "Stroke hold time" },
  { id: "custom_input", constant: false, min: -5, def: 0, max: 5, name: "Custom input" },
  { id: "custom_input_slowness", constant: false, min: 0, def: 0, max: 10, name: "Custom input filter" },
  { id: "elliptical_dab_ratio", constant: false, min: 1, def: 1, max: 10, name: "Elliptical dab: ratio" },
  { id: "elliptical_dab_angle", constant: false, min: 0, def: 90, max: 180, name: "Elliptical dab: angle" },
  { id: "direction_filter", constant: false, min: 0, def: 2, max: 10, name: "Direction filter" },
  { id: "lock_alpha", constant: false, min: 0, def: 0, max: 1, name: "Lock alpha" },
  { id: "colorize", constant: false, min: 0, def: 0, max: 1, name: "Colorize" },
  { id: "posterize", constant: false, min: 0, def: 0, max: 1, name: "Posterize" },
  { id: "posterize_num", constant: false, min: 0.01, def: 0.05, max: 1.28, name: "Posterization levels" },
  { id: "snap_to_pixel", constant: false, min: 0, def: 0, max: 1, name: "Snap to pixel" },
  { id: "pressure_gain_log", constant: true, min: -1.8, def: 0, max: 1.8, name: "Pressure gain" },
]

export const INPUTS: readonly InputInfo[] = [
  { id: "pressure", hardMin: 0, softMin: 0, normal: 0.4, softMax: 1, hardMax: null },
  { id: "random", hardMin: 0, softMin: 0, normal: 0.5, softMax: 1, hardMax: 1 },
  { id: "stroke", hardMin: 0, softMin: 0, normal: 0.5, softMax: 1, hardMax: 1 },
  { id: "direction", hardMin: 0, softMin: 0, normal: 0, softMax: 180, hardMax: 180 },
  { id: "tilt_declination", hardMin: 0, softMin: 0, normal: 0, softMax: 90, hardMax: 90 },
  { id: "tilt_ascension", hardMin: -180, softMin: -180, normal: 0, softMax: 180, hardMax: 180 },
  { id: "speed1", hardMin: null, softMin: 0, normal: 0.5, softMax: 4, hardMax: null },
  { id: "speed2", hardMin: null, softMin: 0, normal: 0.5, softMax: 4, hardMax: null },
  { id: "custom", hardMin: null, softMin: -10, normal: 0, softMax: 10, hardMax: null },
  { id: "direction_angle", hardMin: 0, softMin: 0, normal: 0, softMax: 360, hardMax: 360 },
  { id: "attack_angle", hardMin: -180, softMin: -180, normal: 0, softMax: 180, hardMax: 180 },
  { id: "tilt_declinationx", hardMin: -90, softMin: -90, normal: 0, softMax: 90, hardMax: 90 },
  { id: "tilt_declinationy", hardMin: -90, softMin: -90, normal: 0, softMax: 90, hardMax: 90 },
  { id: "gridmap_x", hardMin: 0, softMin: 0, normal: 0, softMax: 256, hardMax: 256 },
  { id: "gridmap_y", hardMin: 0, softMin: 0, normal: 0, softMax: 256, hardMax: 256 },
  { id: "viewzoom", hardMin: -2.77, softMin: -2.77, normal: 0, softMax: 4.15, hardMax: 4.15 },
  { id: "brush_radius", hardMin: -2, softMin: -2, normal: 0, softMax: 6, hardMax: 6 },
  { id: "barrel_rotation", hardMin: -180, softMin: -180, normal: 0, softMax: 180, hardMax: 180 },
]

export const STATES: readonly string[] = ["x", "y", "pressure", "partial_dabs", "actual_radius", "smudge_ra", "smudge_ga", "smudge_ba", "smudge_a", "last_getcolor_r", "last_getcolor_g", "last_getcolor_b", "last_getcolor_a", "last_getcolor_recentness", "actual_x", "actual_y", "norm_dx_slow", "norm_dy_slow", "norm_speed1_slow", "norm_speed2_slow", "stroke", "stroke_started", "custom_input", "rng_seed", "actual_elliptical_dab_ratio", "actual_elliptical_dab_angle", "direction_dx", "direction_dy", "declination", "ascension", "viewzoom", "viewrotation", "direction_angle_dx", "direction_angle_dy", "attack_angle", "flip", "gridmap_x", "gridmap_y", "declinationx", "declinationy", "dabs_per_basic_radius", "dabs_per_actual_radius", "dabs_per_second", "barrel_rotation"]

/** 설정 색인(MYPAINT_BRUSH_SETTING_*) */
export const S = {
  OPAQUE: 0,
  OPAQUE_MULTIPLY: 1,
  OPAQUE_LINEARIZE: 2,
  RADIUS_LOGARITHMIC: 3,
  HARDNESS: 4,
  SOFTNESS: 5,
  ANTI_ALIASING: 6,
  DABS_PER_BASIC_RADIUS: 7,
  DABS_PER_ACTUAL_RADIUS: 8,
  DABS_PER_SECOND: 9,
  GRIDMAP_SCALE: 10,
  GRIDMAP_SCALE_X: 11,
  GRIDMAP_SCALE_Y: 12,
  RADIUS_BY_RANDOM: 13,
  SPEED1_SLOWNESS: 14,
  SPEED2_SLOWNESS: 15,
  SPEED1_GAMMA: 16,
  SPEED2_GAMMA: 17,
  OFFSET_BY_RANDOM: 18,
  OFFSET_Y: 19,
  OFFSET_X: 20,
  OFFSET_ANGLE: 21,
  OFFSET_ANGLE_ASC: 22,
  OFFSET_ANGLE_VIEW: 23,
  OFFSET_ANGLE_2: 24,
  OFFSET_ANGLE_2_ASC: 25,
  OFFSET_ANGLE_2_VIEW: 26,
  OFFSET_ANGLE_ADJ: 27,
  OFFSET_MULTIPLIER: 28,
  OFFSET_BY_SPEED: 29,
  OFFSET_BY_SPEED_SLOWNESS: 30,
  SLOW_TRACKING: 31,
  SLOW_TRACKING_PER_DAB: 32,
  TRACKING_NOISE: 33,
  COLOR_H: 34,
  COLOR_S: 35,
  COLOR_V: 36,
  RESTORE_COLOR: 37,
  CHANGE_COLOR_H: 38,
  CHANGE_COLOR_L: 39,
  CHANGE_COLOR_HSL_S: 40,
  CHANGE_COLOR_V: 41,
  CHANGE_COLOR_HSV_S: 42,
  SMUDGE: 43,
  PAINT_MODE: 44,
  SMUDGE_TRANSPARENCY: 45,
  SMUDGE_LENGTH: 46,
  SMUDGE_LENGTH_LOG: 47,
  SMUDGE_BUCKET: 48,
  SMUDGE_RADIUS_LOG: 49,
  ERASER: 50,
  STROKE_THRESHOLD: 51,
  STROKE_DURATION_LOGARITHMIC: 52,
  STROKE_HOLDTIME: 53,
  CUSTOM_INPUT: 54,
  CUSTOM_INPUT_SLOWNESS: 55,
  ELLIPTICAL_DAB_RATIO: 56,
  ELLIPTICAL_DAB_ANGLE: 57,
  DIRECTION_FILTER: 58,
  LOCK_ALPHA: 59,
  COLORIZE: 60,
  POSTERIZE: 61,
  POSTERIZE_NUM: 62,
  SNAP_TO_PIXEL: 63,
  PRESSURE_GAIN_LOG: 64,
} as const

/** 입력 색인(MYPAINT_BRUSH_INPUT_*) */
export const I = {
  PRESSURE: 0,
  RANDOM: 1,
  STROKE: 2,
  DIRECTION: 3,
  TILT_DECLINATION: 4,
  TILT_ASCENSION: 5,
  SPEED1: 6,
  SPEED2: 7,
  CUSTOM: 8,
  DIRECTION_ANGLE: 9,
  ATTACK_ANGLE: 10,
  TILT_DECLINATIONX: 11,
  TILT_DECLINATIONY: 12,
  GRIDMAP_X: 13,
  GRIDMAP_Y: 14,
  VIEWZOOM: 15,
  BRUSH_RADIUS: 16,
  BARREL_ROTATION: 17,
} as const

/** 상태 색인(MYPAINT_BRUSH_STATE_*) */
export const ST = {
  X: 0,
  Y: 1,
  PRESSURE: 2,
  PARTIAL_DABS: 3,
  ACTUAL_RADIUS: 4,
  SMUDGE_RA: 5,
  SMUDGE_GA: 6,
  SMUDGE_BA: 7,
  SMUDGE_A: 8,
  LAST_GETCOLOR_R: 9,
  LAST_GETCOLOR_G: 10,
  LAST_GETCOLOR_B: 11,
  LAST_GETCOLOR_A: 12,
  LAST_GETCOLOR_RECENTNESS: 13,
  ACTUAL_X: 14,
  ACTUAL_Y: 15,
  NORM_DX_SLOW: 16,
  NORM_DY_SLOW: 17,
  NORM_SPEED1_SLOW: 18,
  NORM_SPEED2_SLOW: 19,
  STROKE: 20,
  STROKE_STARTED: 21,
  CUSTOM_INPUT: 22,
  RNG_SEED: 23,
  ACTUAL_ELLIPTICAL_DAB_RATIO: 24,
  ACTUAL_ELLIPTICAL_DAB_ANGLE: 25,
  DIRECTION_DX: 26,
  DIRECTION_DY: 27,
  DECLINATION: 28,
  ASCENSION: 29,
  VIEWZOOM: 30,
  VIEWROTATION: 31,
  DIRECTION_ANGLE_DX: 32,
  DIRECTION_ANGLE_DY: 33,
  ATTACK_ANGLE: 34,
  FLIP: 35,
  GRIDMAP_X: 36,
  GRIDMAP_Y: 37,
  DECLINATIONX: 38,
  DECLINATIONY: 39,
  DABS_PER_BASIC_RADIUS: 40,
  DABS_PER_ACTUAL_RADIUS: 41,
  DABS_PER_SECOND: 42,
  BARREL_ROTATION: 43,
} as const

export const SETTINGS_COUNT = 65
export const INPUTS_COUNT = 18
export const STATES_COUNT = 44
